"""Assemble the combined xArm7 + XHand right URDF.

Arm chain  : taken from tasks/direct/simtoolreal/xarm7/xarm7.urdf  (link_base..link7,
             joint1..joint7), meshes copied locally to ./meshes.
Hand subtree: reused verbatim from assets/fr3_xhand/fr3_xhand.urdf (palm + 12 finger
             joints), which already converts cleanly to USD and references the shared
             ../xhand2R32/meshes/*.stl.
Mount      : a flange frame `link8` fixed at link7 (+Z), then `hand_mount` fixes the
             XHand `palm` onto `link8` with a 180 deg flip about Z (same convention the
             fr3_xhand mount uses, so the palm faces out of the flange).

Run with plain python (no isaacsim needed); it only does text surgery.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
XARM7_URDF = os.path.join(
    HERE, "..", "..", "tasks", "direct", "simtoolreal", "xarm7", "xarm7.urdf"
)
FR3_XHAND_URDF = os.path.join(HERE, "..", "fr3_xhand", "fr3_xhand.urdf")
OUT_URDF = os.path.join(HERE, "xarm7_xhand.urdf")

# ---- flange offset: how far past link7's origin (along its +Z) the hand mounts.
# link7's frame is the WRS tcp (tcp offset 0), so a small standoff clears the flange
# mesh. Tune this + the mount rpy after a visual check.
FLANGE_Z = 0.0
# yaw about the flange (link8) Z axis. 180 deg (fr3 convention) + 90 deg = 270 deg, to
# fix the hand-vs-arm rotational misalignment. Flip the sign of the +pi/2 term if it
# ends up rotated the wrong way.
MOUNT_RPY = "0 0 4.71239"  # 270 deg about Z (= pi + pi/2)


def extract_body(urdf_text: str) -> str:
    """Return everything between <robot ...> and </robot> (exclusive)."""
    start = re.search(r"<robot\b[^>]*>", urdf_text)
    end = urdf_text.rfind("</robot>")
    return urdf_text[start.end() : end]


def main() -> None:
    with open(XARM7_URDF) as f:
        arm = extract_body(f.read())

    with open(FR3_XHAND_URDF) as f:
        fr3_xhand = f.read()

    # hand subtree = from the first material def (just after the fr3 arm) to </robot>
    hand_start = fr3_xhand.index('<material name="dim_gray">')
    hand = extract_body(fr3_xhand[hand_start - 5 :]) if False else fr3_xhand[hand_start:]
    hand = hand[: hand.rfind("</robot>")]

    # re-parent the hand mount from the fr3 flange to our link8
    hand = hand.replace('<parent link="fr3_link8" />', '<parent link="link8" />')

    flange = f"""
  <!-- ===================== Flange frame + hand mount ===================== -->
  <link name="link8" />
  <joint name="link8_joint" type="fixed">
    <origin xyz="0 0 {FLANGE_Z}" rpy="0 0 0"/>
    <parent link="link7"/>
    <child link="link8"/>
  </joint>
"""

    # override the reused mount's rpy/origin so it's explicit & easy to tune here
    hand = re.sub(
        r'(<joint name="hand_mount"[^>]*>.*?<origin )xyz="[^"]*" rpy="[^"]*"',
        rf'\g<1>xyz="0 0 0" rpy="{MOUNT_RPY}"',
        hand,
        flags=re.DOTALL,
    )

    out = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by build_urdf.py: xArm7 arm + XHand right (19 DOF). Do not edit by hand. -->
<robot name="xarm7_xhand">
{arm}
{flange}
{hand}
</robot>
"""
    with open(OUT_URDF, "w") as f:
        f.write(out)
    print(f"wrote {OUT_URDF}")


if __name__ == "__main__":
    main()
