"""Build xArm7 with a minimal two-finger parallel gripper."""

from __future__ import annotations

from pathlib import Path


HERE = Path(__file__).resolve().parent
XARM_XHAND_URDF = HERE.parent / "xarm7_xhand" / "xarm7_xhand.urdf"
OUT_URDF = HERE / "xarm7_gripper.urdf"


def main() -> None:
    source = XARM_XHAND_URDF.read_text()
    start = source.index("  <!-- ===================== Links ===================== -->")
    stop = source.index("<material name=\"dim_gray\">")
    arm = source[start:stop].replace(
        'filename="meshes/', 'filename="../xarm7_xhand/meshes/'
    )
    gripper = r"""
  <material name="gripper_dark"><color rgba="0.18 0.18 0.20 1"/></material>
  <material name="pad_rubber"><color rgba="0.05 0.05 0.05 1"/></material>

  <link name="palm">
    <visual><origin xyz="0 0 0.025"/><geometry><box size="0.10 0.055 0.05"/></geometry><material name="gripper_dark"/></visual>
    <collision><origin xyz="0 0 0.025"/><geometry><box size="0.10 0.055 0.05"/></geometry></collision>
    <inertial><origin xyz="0 0 0.025"/><mass value="0.30"/><inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/></inertial>
  </link>
  <joint name="hand_mount" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 4.71239"/>
    <parent link="link8"/><child link="palm"/>
  </joint>

  <link name="thumb_rota_link2">
    <visual><origin xyz="0 0 0.045"/><geometry><box size="0.014 0.035 0.09"/></geometry><material name="pad_rubber"/></visual>
    <collision><origin xyz="0 0 0.045"/><geometry><box size="0.014 0.035 0.09"/></geometry></collision>
    <inertial><origin xyz="0 0 0.045"/><mass value="0.08"/><inertia ixx="0.00006" ixy="0" ixz="0" iyy="0.00006" iyz="0" izz="0.00001"/></inertial>
  </link>
  <joint name="left_finger_joint" type="prismatic">
    <origin xyz="0 0 0.045"/><parent link="palm"/><child link="thumb_rota_link2"/><axis xyz="1 0 0"/>
    <limit lower="0.0" upper="0.055" effort="120" velocity="0.25"/>
  </joint>

  <link name="index_rota_link2">
    <visual><origin xyz="0 0 0.045"/><geometry><box size="0.014 0.035 0.09"/></geometry><material name="pad_rubber"/></visual>
    <collision><origin xyz="0 0 0.045"/><geometry><box size="0.014 0.035 0.09"/></geometry></collision>
    <inertial><origin xyz="0 0 0.045"/><mass value="0.08"/><inertia ixx="0.00006" ixy="0" ixz="0" iyy="0.00006" iyz="0" izz="0.00001"/></inertial>
  </link>
  <joint name="right_finger_joint" type="prismatic">
    <origin xyz="0 0 0.045"/><parent link="palm"/><child link="index_rota_link2"/><axis xyz="-1 0 0"/>
    <limit lower="0.0" upper="0.055" effort="120" velocity="0.25"/>
  </joint>
"""
    out = "<?xml version=\"1.0\"?>\n<!-- Generated by build_urdf.py. -->\n<robot name=\"xarm7_gripper\">\n"
    out += arm + gripper + "\n</robot>\n"
    OUT_URDF.write_text(out)
    print(f"wrote {OUT_URDF}")


if __name__ == "__main__":
    main()
