# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""xArm7 + XHand functional grasping: claw-hammer nail pulling / hammering.

See ``claw_hammer_experiment_plan.md``. The hammer starts in the hand; the policy must
use the two natural affordances of the tool under a constrained arm:

  * ``Hammer-Nail-Token-Direct-v0``      -- MVP-1: align the claw, pull the nail 3 cm.
  * ``Hammer-Nail-Full-Token-Direct-v0`` -- MVP-3: pull 3 cm, switch the tool in hand
    (claw -> hammer face), press the nail back in.

Assets are generated by ``gen_hammer_nail_assets.py`` (run once, see its docstring).
"""

import gymnasium as gym

from . import agents

gym.register(
    id="Hammer-Nail-Token-Direct-v0",
    entry_point=f"{__name__}.hammer_nail_env:HammerNailTokenEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.hammer_nail_env_cfg:HammerNailTokenEnvCfg",
        "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml",
    },
)

gym.register(
    id="Hammer-Nail-Full-Token-Direct-v0",
    entry_point=f"{__name__}.hammer_nail_env:HammerNailTokenEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.hammer_nail_env_cfg:HammerNailFullTokenEnvCfg",
        "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml",
    },
)
